ShopSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopSystem.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            #region 光顧數量
            //記錄光顧數量
            string path = Server.MapPath("~/App_Data/VisitCount.txt");
            string text = System.IO.File.ReadAllText(path);
            int nn = int.Parse(text) + 1;
            System.IO.File.WriteAllText(path, nn.ToString());

            //印出光顧數量
            System.Text.StringBuilder sb1 = new System.Text.StringBuilder();
            for (int i = 1; i <= 5 - nn.ToString().Length; i++)
                sb1.Append("<img src='/images/number/0.gif' />");
            for (int i = 0; i < nn.ToString().Length; i++)
                sb1.Append(string.Format("<img src='/images/number/{0}.gif' />", nn.ToString().Substring(i, 1)));

            ViewData["VisitNum"] = sb1.ToString();
            #endregion

            #region 列出商品
            DB.DB mydb = new DB.DB();
            DB.IProduct ip = new DB.Impl_Product(mydb.Connection);
            DataTable tt = ip.GetProductList();

            List<Models.ProductInfo> ps = new List<Models.ProductInfo>();
            if (tt != null)
            {
                foreach (DataRow r in tt.Rows)
                {
                    Models.ProductInfo pi = new Models.ProductInfo();
                    pi.ID = (int)r["proID"];
                    pi.Name = r["proName"].ToString();
                    pi.PTName = r["PTName"].ToString();
                    pi.Pic = r["proPic"].ToString();
                    ps.Add(pi);
                }
            }
            #endregion

            #region 列出分類
            if (Session["proTypes"] == null)
            {
                System.Text.StringBuilder sb2 = new System.Text.StringBuilder();
                sb2.Append("<table>");
                DB.DB mydb2 = new DB.DB();
                DB.IProduct ip2 = new DB.Impl_Product(mydb2.Connection);
                DataTable tt2 = ip2.GetProductType();
                if (tt2 != null)
                {
                    foreach (DataRow r in tt2.Rows)
                    {
                        sb2.Append(string.Format("<tr><td><a style=\"text-align:center\" href=\"/Home/ProductType?type={0}\">", r["PTID"].ToString()));
                        sb2.Append(string.Format("<img src='/images/shop/{0}' />", r["PTPic"].ToString()));
                        sb2.Append("</a></td></tr>");
                    }
                }
                sb2.Append("</table>");
                Session["proTypes"] = sb2.ToString();
            }
            ViewData["proTypes"] = Session["proTypes"];
            #endregion

            return View(ps);
        }
        public ActionResult ProductType(int? type, int? page)
        {
            if (page == null) page = 1;
            if (type == null) type = 0;

            DB.DB mydb = new DB.DB("SQLAdmin", "admin1234");
            DB.IProduct ip = new DB.Impl_Product(mydb.Connection);
            DataTable tt = ip.GetProductListByType(type.Value);
            
            if (tt == null) tt = new DataTable();
            int count = tt.Rows.Count;

            int totalPage = 1;
            if (count > 5)
                totalPage = (int)Math.Ceiling(count / 5.0);

            if (page > totalPage)
                return RedirectToAction("ProductType", new { type });

            List<Models.ProductInfo> ps = new List<Models.ProductInfo>();
            foreach (DataRow r in tt.Rows)
            {
                int countID = Convert.ToInt32(r["countID"]);
                if (countID <= 5 * (page.Value - 1) || countID > 5 * page.Value)
                    continue;

                Models.ProductInfo pi = new Models.ProductInfo();
                pi.ID = (int)r["proID"];
                pi.Name = r["proName"].ToString();
                pi.Note = r["proNote"].ToString();
                pi.PTName = r["PTName"].ToString();
                pi.Price = Convert.ToInt32(r["proPrice"]);
                pi.Stock = Convert.ToInt32(r["proStock"]);
                pi.Pic = r["proPic"].ToString();
                ps.Add(pi);
            }


            //頁碼
            System.Text.StringBuilder sb2 = new System.Text.StringBuilder();
            for (int i = 1; i <= totalPage; i++)
            {
                if (i == page.Value)
                    sb2.Append(i).Append("&nbsp;&nbsp;");
                else
                    sb2.Append(string.Format("<a style=\"text-decoration:underline\" href='{0}'>{1}</a>&nbsp;&nbsp;", Url.Action("ProductType", new { type, page = i }), i));
            }
            ViewData["PageLink"] = sb2.ToString();
            ViewData["proTypes"] = Session["proTypes"];

            return View(ps);
        }
        public ActionResult ProductSearch(string proName, int? page)
        {
            if (page == null) page = 1;
            DataTable tt;
            if (proName == null)
                tt = new DataTable();
            else
            {
                DB.DB mydb = new DB.DB("SQLAdmin", "admin1234");
                DB.IProduct ip = new DB.Impl_Product(mydb.Connection);
                tt = ip.SearchProductsByName(proName);
            }

            if (page == null) page = 1;
            if (tt == null) tt = new DataTable();
            int count = tt.Rows.Count;

            int totalPage = 1;
            if (count > 5)
                totalPage = (int)Math.Ceiling(count / 5.0);

            if (page > totalPage)
                return RedirectToAction("ProductSearch", new { proName });

            List<Models.ProductInfo> ps = new List<Models.ProductInfo>();
            foreach (DataRow r in tt.Rows)
            {
                int countID = Convert.ToInt32(r["countID"]);
                if (countID <= 5 * (page.Value - 1) || countID > 5 * page.Value)
                    continue;

                Models.ProductInfo pi = new Models.ProductInfo();
                pi.ID = (int)r["proID"];
                pi.Name = r["proName"].ToString();
                pi.Note = r["proNote"].ToString();
                pi.PTName = r["PTName"].ToString();
                pi.Price = Convert.ToInt32(r["proPrice"]);
                pi.Stock = Convert.ToInt32(r["proStock"]);
                pi.Pic = r["proPic"].ToString();
                ps.Add(pi);
            }
            
            //頁碼
            System.Text.StringBuilder sb2 = new System.Text.StringBuilder();
            for (int i = 1; i <= totalPage; i++)
            {
                if (i == page.Value)
                    sb2.Append(i).Append("&nbsp;&nbsp;");
                else
                    sb2.Append(string.Format("<a style=\"text-decoration:underline\" href='{0}'>{1}</a>&nbsp;&nbsp;", Url.Action("ProductSearch", new { proName, page = i }), i));
            }
            ViewData["PageLink"] = sb2.ToString();
            ViewData["proTypes"] = Session["proTypes"];

            return View(ps);
        }
        [HttpPost]
        public ActionResult SentSearch(string Search)
        {
            return RedirectToAction("ProductSearch", new { proName = Search });
        }
        public ActionResult Product(int? pid)
        {
            if (pid == null)
                pid = 1;

            DB.DB mydb = new DB.DB();
            DB.IProduct ip = new DB.Impl_Product(mydb.Connection);
            Dictionary<string, object> dp = ip.GetSingleProduct(pid.Value);

            if (dp == null || (int)dp["proState"] == 0)
                RedirectToAction("Product");

            Models.ProductInfo pi = new Models.ProductInfo();
            pi.ID = (int)dp["proID"];
            pi.Name = dp["proName"].ToString();
            pi.PTName = dp["PTName"].ToString();
            pi.Note = dp["proNote"].ToString();
            pi.Price = Convert.ToInt32(dp["proPrice"]);
            pi.Stock = Convert.ToInt32(dp["proStock"]);
            pi.Pic = dp["proPic"].ToString();

            ViewData["proTypes"] = Session["proTypes"];

            return View(pi);
        }
    }
}

ShopSystem/Controllers/ShopCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopSystem.Controllers
{
    [App_Code.CustomerLoginFilter]
    public class ShopCartController : Controller
    {
        // GET: ShopCart
        public ActionResult Index()
        {
            if (Session["Cart"] == null)
                return RedirectToAction("Index", "Home");

            HashSet<Models.CartItem> myCart =
                Session["Cart"] as HashSet<Models.CartItem>;

            int shipping = 0;
            double amount = 0;
            int total = 0;

            foreach (Models.CartItem ii in myCart)
            {
                amount += ii.SubTotal;
            }

            if (amount < 1000)
                shipping = 150;
            else if (amount < 2000)
                shipping = 80;

            total = (int)Math.Round(amount) + shipping;

            ViewData["Shipping"] = shipping;
            ViewData["Amount"] = (int)Math.Round(amount);
            ViewData["Total"] = total;

            return View();
        }

        public ActionResult AddToCart(int? pid)
        {
            if (pid == null)
                return RedirectToAction("Index", "Home");

            HashSet<Models.CartItem> myCart = null;

            if (Session["Cart"] == null)
                myCart = new HashSet<Models.CartItem>();
            else
                myCart = Session["Cart"] as HashSet<Models.CartItem>;

            Models.CartItem ci = new Models.CartItem();
            ci.ID = pid.Value;

            if (myCart.Contains(ci))
                return RedirectToAction("Index");

            DB.DB mydb = new DB.DB();
            DB.IProduct ip = new DB.Impl_Product(mydb.Connection);
            Dictionary<string, object> pp = ip.GetSingleProduct(pid.Value);

            if (pp == null)
                return RedirectToAction("Index", "Home");

            ci.ID = Convert.ToInt32(pp["proID"]);
            ci.Name = pp["proName"].ToString();
            ci.Stock = Convert.ToInt32(pp["proStock"]);
            ci.Quantity = 1;
            ci.Price = Convert.ToInt32(pp["proPrice"]);
            myCart.Add(ci);
            Session["Cart"] = myCart;
            return RedirectToAction("Index");
        }

        public ActionResult ClearCart()
        {
            Session["Cart"] = null;
            Session.Remove("Cart");
            return RedirectToAction("Index", "Home");
        }

        public ActionResult UpdateCart()
        {
            if (Session["Cart"] == null)
                return RedirectToAction("Index", "Home");

            HashSet<Models.CartItem> myCart =
                Session["Cart"] as HashSet<Models.CartItem>;

            foreach (Models.CartItem ci in myCart)
            {
                int num = int.Parse(Request.Form["pc_" + ci.ID]);
                ci.Quantity = num;
            }
            myCart.RemoveWhere(IsZero);

            if (myCart.Count == 0)
                return ClearCart();

            Session["Cart"] = myCart;
            return RedirectToAction("Index");
        }

        private bool IsZero(Models.CartItem ci)
        {
            return ((ci.Quantity) == 0);
        }

        public ActionResult CheckOut()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PlaceOrder(Models.Order order)
        {
            if (Session["Cart"] == null)
                return RedirectToAction("Index", "Home");

            DB.DB mydb = new DB.DB();
            DB.ICustomer ic = new DB.Impl_Customer(mydb.Connection);
            order.custID = ic.GetCustIDByPhone(Session["Login"].ToString());

            DB.DB mydb2 = new DB.DB("SQLAdmin", "admin1234");
            DB.IOrder io = new DB.Impl_Order(mydb2.Connection);
            order.orderID = io.AddNewOrder(order.custID, order.rcptName, order.rcptPhone, order.rcptAddr, order.DTID, order.Shipping, order.orderNote);
            
            HashSet<Models.CartItem> myCart =
                Session["Cart"] as HashSet<Models.CartItem>;

            List<Dictionary<string, object>> items = new List<Dictionary<string, object>>();

            foreach (Models.CartItem ii in myCart)
            {
                Dictionary<string, object> temp = new Dictionary<string, object>();
                temp["proID"] = ii.ID;
                temp["Quantity"] = ii.Quantity;
                items.Add(temp);
            }

            DB.DB mydb3 = new DB.DB("SQLAdmin", "admin1234");
            DB.IOrder io2 = new DB.Impl_Order(mydb3.Connection);
            bool finish = io2.AddCartItems(order.orderID, items);

            if(finish)
                return RedirectToAction("FinishOrder", new { msg = "已完成訂單!請至個人中心查看!" });
            else
                return RedirectToAction("FinishOrder", new { msg = "訂單失敗!請重新下訂貨聯絡客服!" });
        }

        public ActionResult FinishOrder(string msg)
        {
            ViewData["msg"] = msg;
            return View();
        }
    }
}

ShopSystem/Views/Home/Index.cshtml
@{
    ViewBag.Title = "首頁";
}

@model List<ShopSystem.Models.ProductInfo>

@section Style
{
    <style>
        #ProductList {
            border-top: 3px #ffa900 solid;
            border-bottom: 3px #0094ff solid;
        }
        #ProductList td {
            text-align: center;
        }
    </style>
}

<h2>歡迎光臨! 您是第&nbsp;@Html.Raw(ViewData["VisitNum"])&nbsp;位光臨本站的訪客!</h2>

<table align="center">
    <tr>
        <td class="ChooseL">
            @Html.Raw(ViewData["proTypes"])
        </td>
        <td class="ChooseR">
            <table id="ProductList" cellpadding="10">
                <tr>
                    @{
                        int i = 0;
                        foreach (var pp in Model)
                        {
                            <td>
                                <a style="text-align:center" href="/Home/Product?pid=@pp.ID">
                                    <img src="~/images/shop/@pp.PTName/@pp.Pic" />
                                    <br /> @pp.Name
                                </a>
                            </td>
                            i++;
                            if (i % 4 == 0)
                            {
                            @:</tr><tr>
                            }
                        }
                    }
                </tr>
            </table>
        </td>
    </tr>
</table>

ShopSystem/Views/Home/Product.cshtml
@{
    ViewBag.Title = "商品資訊";
}
@model ShopSystem.Models.ProductInfo
<h2>商品資訊</h2>
<p>&nbsp;</p>
<table align="center">
    <tr>
        <td class="ChooseL">
            @Html.Raw(ViewData["proTypes"])
        </td>
        <td class="ChooseR">
            <p>@Model.Name</p>
            <p><img src="~/images/shop/@Model.PTName/@Model.Pic" /></p>
            <p>商品介紹：</p>
            @Html.Raw(Model.Note)
            <p>
                價格：&nbsp;@Model.Price&nbsp;&nbsp;&nbsp;&nbsp;庫存：&nbsp;@Model.Stock&nbsp;&nbsp;&nbsp;&nbsp;
                @if (Model.Stock > 0)
                {
                    <a href="@Url.Action("AddToCart", "ShopCart", new { pid = Model.ID })">
                        <img src="~/images/shop/cart_add.png" title="加入購物車" />
                    </a>
                }
                else
                {
                    <img src="~/images/shop/sold_out.png" title="已售完" />
                }
            </p>
        </td>
    </tr>
</table>

ShopSystem/Views/Home/ProductSearch.cshtml
@{
    ViewBag.Title = "商品搜尋列表";
}
@model List<ShopSystem.Models.ProductInfo>

@section Style
{
    <style>
        #ProductList tr:nth-child(odd) {
            background-color: rgba(255, 223, 161, 0.25);
        }
        #ProductList tr:nth-child(even) {
            background-color: rgba(161, 215, 255, 0.25);
        }
    </style>
}

<h2>商品搜尋列表</h2>
<p>&nbsp;</p>
<table align="center">
    <tr>
        <td class="ChooseL">
            @Html.Raw(ViewData["proTypes"])
        </td>
        <td class="ChooseR">
            <table id="ProductList" cellpadding="30" cellspacing="0">
                @if (Model.Count == 0)
                {
                    @:查無相關商品!
                }
                @foreach (var pp in Model)
                {
                    <tr>
                        <td align="center">
                            <a href="/Home/Product?pid=@pp.ID">
                                <img src="~/images/shop/@pp.PTName/@pp.Pic" />
                            </a>
                        </td>
                        <td width="500">
                            <a href="/Home/Product?pid=@pp.ID">
                                <p>@pp.Name</p>
                            </a>
                            <p>
                                價格：@pp.Price&nbsp;&nbsp;&nbsp;&nbsp;庫存：@pp.Stock
                            </p>
                        </td>
                        <td width="100">
                            @if (pp.Stock > 0)
                            {
                                <a href="@Url.Action("AddToCart", "ShopCart", new { pid = pp.ID })">
                                    <img src="~/images/shop/cart_add.png" title="加入購物車" />
                                </a>
                            }
                            else
                            {
                                <img src="~/images/shop/sold_out.png" title="已售完" />
                            }
                        </td>
                    </tr>
                }
            </table>
        </td>
    </tr>
</table>



<p>&nbsp;</p>
<p style="text-align:center">@Html.Raw(ViewData["PageLink"])</p>

ShopSystem/Views/Home/ProductType.cshtml
@{
    ViewBag.Title = "商品類別列表";
}
@model List<ShopSystem.Models.ProductInfo>

@section Style
{
    <style>
        #ProductList tr:nth-child(odd) {
            background-color: rgba(255, 223, 161, 0.25);
        }

        #ProductList tr:nth-child(even) {
            background-color: rgba(161, 215, 255, 0.25);
        }
    </style>
}

<h2>商品類別列表</h2>
<p>&nbsp;</p>
<table align="center">
    <tr>
        <td class="ChooseL">
            @Html.Raw(ViewData["proTypes"])
        </td>
        <td class="ChooseR">
            <table id="ProductList" cellpadding="30" cellspacing="0">
                @if (Model.Count == 0)
                {
                    @:查無相關類別商品!
                }
                @foreach (var pp in Model)
                {
                    <tr>
                        <td align="center">
                            <a href="/Home/Product?pid=@pp.ID">
                                <img src="~/images/shop/@pp.PTName/@pp.Pic" />
                            </a>
                        </td>
                        <td width="500">
                            <a href="/Home/Product?pid=@pp.ID">
                                <p>@pp.Name</p>
                            </a>
                            <p>
                                價格：@pp.Price&nbsp;&nbsp;&nbsp;&nbsp;庫存：@pp.Stock
                            </p>
                        </td>
                        <td width="100">
                            @if (pp.Stock > 0)
                            {
                                <a href="@Url.Action("AddToCart", "ShopCart", new { pid = pp.ID })">
                                    <img src="~/images/shop/cart_add.png" title="加入購物車" />
                                </a>
                            }
                            else
                            {
                                <img src="~/images/shop/sold_out.png" title="已售完" />
                            }
                        </td>
                    </tr>
                }
            </table>
        </td>
    </tr>
</table>



<p>&nbsp;</p>
<p style="text-align:center">@Html.Raw(ViewData["PageLink"])</p>